export enum Events {
	CONNECTED = "CONNECTED",
	CONNECTED_AND_WAITING = "CONNECTED_AND_WAITING",
	USER_PREF = "USER_PREF",
	VALID_PLACEMENT = "VALID_PLACEMENT",
	START_GAME = "START_GAME",
	ROOM_DATA = "ROOM_DATA",
	SETUP_SHIPS = "SETUP_SHIPS",
	FIRE_SHOT = "FIRE_SHOT",
	RECEIVED_SHOT = "RECEIVED_SHOT",
	OPPONENT_QUIT = "OPPONENT_QUIT",
}